create table if not exists public.wedding_wishes (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.wedding_wishes enable row level security;

create policy "Allow insert for anyone"
on public.wedding_wishes
for insert
to anon, authenticated
with check (true);

create policy "Allow read for anyone"
on public.wedding_wishes
for select
to anon, authenticated
using (true);
